import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "../globals.css";
import Footer from "../components/Footer";
import Header from "../components/Header";
import SessionProvider from "../components/SessionProvider";
import type { Locale } from "@/lib/i18n/translations";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Step Shop",
  description: "Generated by create next app",
};

export default async function Layout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies()
  const locale = (cookieStore.get('locale')?.value || 'ru') as Locale

  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased outline-hidden`}
    >
    <body className="min-h-full flex flex-col bg-gray-600">
    <SessionProvider>
      <Header initialLocale={locale} />
      {children}
      <Footer />
    </SessionProvider></body>
    </html>
  );
}



